version: '3.5'

services:
    db:
        image: postgres:12.1
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        environment:
            POSTGRES_USER: bovoyages
            POSTGRES_PASSWORD: bovoyages
            POSTGRES_DB: bovoyages
        ports:
            - "5432:5432"
volumes:
    db-data: {}
